Docker MySQLの初期設定等
ari1021/chat pull request #20
Opened 2021-01-13 12:15 UTC by ari1021

closes #19

2021-01-13 12:19 UTC, ari1021 commented
次のような挙動をするのですが，原因わかりませんか？
1. docker-compose upを初めてした時に「connection refused」というエラーが出る．
2. 一度ctrl+cで中断して，(コード類は何も変えずに)もう一度docker-compose upすればエラーが出ずにテーブルが作成される

2021-01-13 14:57 UTC, konnyaku256 commented
んー、ちょっと謎の挙動だね、、

効果ないかもしれないけど、次の手順ならどうだろうか？

### コンテナを削除してから起動し直す
```
docker-compose down
docker-compose up
```
それか
### コンテナ起動時にキャッシュを無視してビルドし直してから起動する
```
docker-compose up --build
```

いちおう手元ではupするだけで起動できてたのでイメージかコンテナが更新されてないのかも
いちおう実行結果も貼っておくね
```
websocket on  pr-20 via 🐹 v1.15.6
❯ docker-compose up
Creating network "websocket_mysql_net" with the default driver
Creating docker_db ... done
Creating websocket_api_1 ... done
Attaching to docker_db, websocket_api_1
docker_db | 2021-01-13 14:47:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
docker_db | 2021-01-13 14:47:22+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
docker_db | 2021-01-13 14:47:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
docker_db | 2021-01-13T14:47:22.479734Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
docker_db | 2021-01-13T14:47:22.489032Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
docker_db | 2021-01-13T14:47:22.507398Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
api_1  | [14:47:23][SRC] : Watching 15 file/s 18 folder/s
api_1  | [14:47:23][SRC] : Build started
docker_db | 2021-01-13T14:47:23.415413Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
docker_db | 2021-01-13T14:47:23.737186Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
docker_db | 2021-01-13T14:47:23.924137Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
docker_db | 2021-01-13T14:47:23.924791Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
docker_db | 2021-01-13T14:47:23.937685Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
docker_db | 2021-01-13T14:47:24.093904Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
api_1  | [14:47:27][SRC] : Build completed in 4.574 s
api_1  | [14:47:27][SRC] : Running..
api_1  | [14:47:28][SRC] :    ____    __
api_1  | [14:47:28][SRC] :   / __/___/ /  ___
api_1  | [14:47:28][SRC] :  / _// __/ _ \/ _ \
api_1  | [14:47:28][SRC] : /___/\__/_//_/\___/ v4.1.17
api_1  | [14:47:28][SRC] : High performance, minimalist Go web framework
api_1  | [14:47:28][SRC] : https://echo.labstack.com
api_1  | [14:47:28][SRC] : ____________________________________O/_______
api_1  | [14:47:28][SRC] :                                     O\
api_1  | [14:47:28][SRC] : ⇨ http server started on [::]:8080

```

2021-01-13 16:01 UTC, ari1021 commented
ありがとうございます．
やっぱり`docker-compose down`しても`docker-compose up --build`しても1回目はエラー吐くみたいです(？)
一応実行結果を貼っておきます！
```bash
Successfully built 64a65dd11bae
Successfully tagged chat_api:latest
Starting docker_db ... done
Recreating chat_api_1 ... done
Attaching to docker_db, chat_api_1
docker_db | 2021-01-13 15:49:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
docker_db | 2021-01-13 15:49:15+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
docker_db | 2021-01-13 15:49:15+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
docker_db | 2021-01-13 15:49:15+00:00 [Note] [Entrypoint]: Initializing database files
docker_db | 2021-01-13T15:49:15.720648Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.22) initializing of server in progress as process 44
docker_db | 2021-01-13T15:49:15.752264Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
docker_db | 2021-01-13T15:49:15.769032Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
api_1  | [15:49:24][SRC] : Watching 15 file/s 14 folder/s
api_1  | [15:49:24][SRC] : Build started
docker_db | 2021-01-13T15:49:25.044668Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
docker_db | 2021-01-13T15:49:42.694183Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
docker_db | 2021-01-13 15:50:08+00:00 [Note] [Entrypoint]: Database files initialized
docker_db | 2021-01-13 15:50:08+00:00 [Note] [Entrypoint]: Starting temporary server
docker_db | 2021-01-13T15:50:09.204986Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 89
docker_db | 2021-01-13T15:50:09.227373Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
docker_db | 2021-01-13T15:50:09.368224Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
docker_db | 2021-01-13T15:50:11.700401Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
docker_db | 2021-01-13T15:50:12.676010Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
docker_db | 2021-01-13T15:50:13.812627Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
docker_db | 2021-01-13T15:50:13.814585Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
docker_db | 2021-01-13T15:50:13.836581Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
docker_db | 2021-01-13T15:50:14.062890Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
docker_db | 2021-01-13 15:50:14+00:00 [Note] [Entrypoint]: Temporary server started.
docker_db | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
docker_db | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
api_1  | [15:50:39][SRC] : Build completed in 75.109 s
api_1  | [15:50:39][SRC] : Running..
api_1  | [15:50:40][SRC] : 2021/01/13 15:50:40 /go/src/db/db.go:25
// エラー場所
api_1  | [15:50:40][SRC] : [error] failed to initialize database, got error dial tcp 172.21.0.2:3306: connect: connection refused
// エラー場所
api_1  | [15:50:40][SRC] : panic: runtime error: invalid memory address or nil pointer dereference
api_1  | [15:50:40][SRC] : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7cd9d6]
api_1  | [15:50:40][SRC] : goroutine 1 [running]:
api_1  | [15:50:40][SRC] : gorm.io/gorm.(*DB).Session(0x0, 0xc00031fd98, 0x7f2e554fed30)
api_1  | [15:50:40][SRC] : 	/go/pkg/mod/gorm.io/gorm@v1.20.11/gorm.go:162 +0x36
api_1  | [15:50:40][SRC] : gorm.io/gorm.(*DB).Migrator(0x0, 0x40fc78, 0x30)
api_1  | [15:50:40][SRC] : 	/go/pkg/mod/gorm.io/gorm@v1.20.11/migrator.go:10 +0x50
api_1  | [15:50:40][SRC] : gorm.io/gorm.(*DB).AutoMigrate(0x0, 0xc000273320, 0x3, 0x3, 0x4, 0xa196e4)
api_1  | [15:50:40][SRC] : 	/go/pkg/mod/gorm.io/gorm@v1.20.11/migrator.go:15 +0x2b
api_1  | [15:50:40][SRC] : github.com/ari1021/websocket/db.Migrate(...)
api_1  | [15:50:40][SRC] : 	/go/src/db/db.go:33
api_1  | [15:50:40][SRC] : github.com/ari1021/websocket/server/api.NewEcho(0xc00026e940, 0xa3de48)
api_1  | [15:50:40][SRC] : 	/go/src/server/api/router.go:29 +0x646
api_1  | [15:50:40][SRC] : main.main()
api_1  | [15:50:40][SRC] : 	/go/src/main.go:19 +0x179
docker_db | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
docker_db | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
docker_db | 2021-01-13 15:50:44+00:00 [Note] [Entrypoint]: Creating database database
docker_db | 2021-01-13 15:50:44+00:00 [Note] [Entrypoint]: Creating user user
docker_db | 2021-01-13 15:50:44+00:00 [Note] [Entrypoint]: Giving user user access to schema database
docker_db | 
docker_db | 2021-01-13 15:50:44+00:00 [Note] [Entrypoint]: Stopping temporary server
docker_db | 2021-01-13T15:50:44.491256Z 13 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.22).
docker_db | 2021-01-13T15:50:47.447249Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.22)  MySQL Community Server - GPL.
docker_db | 2021-01-13 15:50:47+00:00 [Note] [Entrypoint]: Temporary server stopped
docker_db | 
docker_db | 2021-01-13 15:50:47+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
docker_db | 
docker_db | 2021-01-13T15:50:47.877229Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
docker_db | 2021-01-13T15:50:47.893883Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
docker_db | 2021-01-13T15:50:47.920865Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
docker_db | 2021-01-13T15:50:49.323943Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
docker_db | 2021-01-13T15:50:49.915688Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
docker_db | 2021-01-13T15:50:50.273642Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
docker_db | 2021-01-13T15:50:50.274024Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
docker_db | 2021-01-13T15:50:50.292030Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
docker_db | 2021-01-13T15:50:50.581701Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.

```

2021-01-14 02:13 UTC, Takumaron commented on docker-compose.yaml
> +      DB_ADDRESS: docker_db
コンテナ名ではなくて，サービス名にしないといけないです！

```suggestion
      DB_ADDRESS: db
```

2021-01-14 05:49 UTC, ari1021 commented on docker-compose.yaml
> +      DB_ADDRESS: docker_db
ありがとうございます，修正しました．

2021-01-14 08:14 UTC, Khmer495 requested changes

2021-01-14 08:14 UTC, Khmer495 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
```suggestion
	DeletedAt *gorm.DeletedAt `gorm:"index"`
```
DeletedAtはnullの場合もあるので、型をポインタにする必要がある！
もしくは`room.go`で使ってるように`gorm.Model`を使うのもあり！

2021-01-14 08:14 UTC, Khmer495 commented on model/user.go
> +	// refreshToken string
コメントアウトされてるけど、ここもnullの可能性があるのでポインタにする必要あり！

2021-01-14 08:14 UTC, Khmer495 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
一応db繋がらなくてエラーはくこともあるので、エラー処理しといたほうが良いかも？

2021-01-14 08:52 UTC, ari1021 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
nullの可能性があるものは型をpointerにしないといけないというルールがgormにはあるってことですか？  
また，https://gorm.io/ja_JP/docs/models.html#Embedded-Struct にあるように，gorm.Modelを使うとDeletedAtは型がpointerではないと思うのですがどうですか？

2021-01-14 08:53 UTC, ari1021 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
NewConnection内でエラー処理を行なっているのですが，
- NewConnection内とNewEcho内の両方でエラー処理を行なった方がいい
- NewEcho内でのみエラー処理を行なった方がいい

のどっちがいいでしょうか？

2021-01-14 09:01 UTC, Khmer495 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
`gorm.DeletedAt`がおそらく`*time.Time`になってるはず！
なんでポインタにしなくちゃいけないかというと、go側でnullを扱えるようにするため
例えばint型のカラムがあって値を指定せずにdbにcreateすると、goのintのデフォルト値である0が保存される
これを*int型にすることでNullが保存されるようになる
取り出すときも同様！

2021-01-14 09:13 UTC, ari1021 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
>なんでポインタにしなくちゃいけないかというと、go側でnullを扱えるようにするため
例えばint型のカラムがあって値を指定せずにdbにcreateすると、goのintのデフォルト値である0が保存される
これを*int型にすることでNullが保存されるようになる
取り出すときも同様！

理解しました．  
調べてみたら，
`DeletedAt`
 ↓
`type DeletedAt sql.NullTime`
↓
```
type NullTime struct {
	Time  time.Time
	Valid bool // Valid is true if Time is not NULL
}
```
こんな感じだったのですが，

2021-01-14 09:18 UTC, Khmer495 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
NewConnection内ではエラーを拾ってpanicを起こさないようにしてるだけで、エラー時にどういう挙動を行うかみたいな処理は行っていない
dbにコネクションはれなければapiサーバーが動かないので、retryする処理を入れるとかapiサーバー落とすとかの処理を入れたほうが良いかも（他の21卒の方どうですかね
まぁここは起動時にのみ走る処理で、エラー起きたらログが走るか落ちるかですぐ確認できるので、そんなに大事なところではないけど！

エラー処理を書く場所は必要範囲内で一番はやいところでいいと思う
今回でいうとコネクションはいたときにはくエラーを他の場所で扱うことはないと思うから、もうNewConnection内でエラー処理完結させて、返り値からエラーを消してもいいと思う

他のケースだと、例えばAPIのgetでid指定でdbを見にいって、そのidが存在しないときを考える
書き方にもよるけどdbがサーバーエラーを出すとして、そのままだとステータスコード500になる
クライアントには404(NotFound)で返したいときにはエラーを伝搬させてechoの部分まで渡して上げる必要がある

2021-01-14 09:29 UTC, Khmer495 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
sqlパッケージはgolangの標準パッケージで、validの部分をfalseにするとデフォルト値ではなくnullになる仕様かな
gorm.DeletedAtに関してはgorm側でvalidの設定を裏でいい感じにやってくれているので、コード書く人はvalidを気にせずtimeの部分だけでnullを扱うことができるようになっているっぽい

ただstringとかintとかに関してはいい感じのものが用意されてないっぽいので、sql.NullStringとかsql.NullInt64とかでvalidもmodelに含めながら頑張るか、ポインタ使うかって感じで、後者が多いかな？
https://qiita.com/taizo/items/3e0b1ca583d8fe2a62a5

2021-01-14 09:30 UTC, Khmer495 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
デフォルト値って言ってるの全部ゼロ値の間違い！

2021-01-14 10:54 UTC, ari1021 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
ありがとうございます．  
下で指摘しているtokenとかはpoiterを使うように修正しておきます！

2021-01-14 10:59 UTC, ari1021 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
ひとまず今回はNewConnectionを返り値connだけにしておいて，
NewConnection内で
```
if err!=nil {
    panic(err)
}
return conn
```
みたいな形でいけそうですか？

2021-01-14 10:59 UTC, ari1021 commented on model/user.go
> +	// refreshToken string
修正しました

2021-01-14 15:35 UTC, konnyaku256 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
@ari1021 @Khmer495 panicでもプログラム終了させられるんだけど、これだとコード見に行かないと何でpanic扱いになったかわかりづらいので

NewConnectionでerrorオブジェクトも返すようにエラーハンドリングしておいて、
```go
if err != nil {
    return nil, fmt.Errorf("failed to open MySQL: %w", err)
}
```

conn, err :=db.NewConnection()のところで`log.Fatal(err)`でプログラム終了させるのを勧めたい！
```go
conn, err :=db.NewConnection()
if err != nil {
	log.Fatal(err)
}
```

※もちろん、ここで終了じゃなくてretryするようにしてもいいんだけど、接続できなかったとき場合に最終的には終了するようにしておくのがいいかな！

2021-01-14 17:33 UTC, ari1021 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
`panic`ではなくて`log.Fatal`を使うのはなぜでしょうか？  
少し調べた感じでは，`panic`と`log.Fatal`のどっちを使うのかみたいな論争が見つかったので恐らく微妙な感じなのかなと思うのですが．．．  
個人的な意見では，`log.Fatal`だと内部でos.Exit()が呼ばれ，defer文が実行されずに終わってしまうから`panic`の方がいいのかなと思っていました．  
また，NewConnectionでerrorを返すなら，NewEchoでもerrorを返してあげて，main関数内でerror処理をするのもいいかなと思っていたのですがどうでしょうか？

2021-01-15 04:09 UTC, konnyaku256 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
終了の直前で必ず実行されてほしい処理があればpanic()させてdefer func()にその処理を書くのが良さそうだね
でなければos.Exit()するだけでよいと思う

エラーハンドリングする箇所はその関数を呼び出したスコープとしておくのはどうかな？
NewConnectionのエラーはNewEcho内でハンドリング、NewEchoのエラーはmain関数内でハンドリングする感じ

2021-01-15 12:16 UTC, ari1021 commented on server/api/router.go
> +	conn, _ := db.NewConnection()
修正しました！

2021-01-15 14:47 UTC, konnyaku256 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
@ari1021 あとはポインタを使うように修正するだけかな？
https://github.com/ari1021/chat/pull/20/files#r557161853

2021-01-15 15:05 UTC, ari1021 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
@Khmer495 
これはDeletedAtがgorm側でうまくやってくれているのでpointerにする必要がないという話になっていたのと思うのですがどうでしたか？

2021-01-16 08:49 UTC, Khmer495 commented on model/user.go
> +	DeletedAt gorm.DeletedAt `gorm:"index"`
型がgorm.DeletedなのでポインタじゃなくてOK!

2021-01-16 08:54 UTC, konnyaku256 approved these changes
:yosasou:

2021-01-16 10:35 UTC, Khmer495 commented on server/api/router.go
> +	}
レビュー抜けてて申しわけない
`router.go`の責務的にここでmigrateをするのではなく、`db.NewConnection()`の中でやったほううがよさそう！（もっと厳密に言うと、router.goには初期化処理をすべて終えたconnをダイレクトに渡したほうが良さそう）

2021-01-16 10:37 UTC, Khmer495 commented
いまmodelのstructのタグに、db用のものとrequestのvalidation用のものが両方付いてると思うけど、将来的にrequest用のものは別のstructを定義する可能性がある（dbとrequestの項目が異なる場合）ことを伝えておく！

2021-01-16 12:58 UTC, ari1021 commented on server/api/router.go
> +	}
`db.NewConnection()`内で`db.Migrate()`を呼び出すようにした方がいいということですか？

2021-01-16 13:31 UTC, Khmer495 commented on server/api/router.go
> +	}
そう！

2021-01-16 14:08 UTC, ari1021 commented on server/api/router.go
> +	}
修正しました！

2021-01-16 16:00 UTC, Khmer495 commented on server/api/router.go
> +	}
この場合migrateの関数は外部パッケージから呼び出さないので小文字でOK！

2021-01-16 16:19 UTC, ari1021 commented on server/api/router.go
> +	}
そうですね，小文字にしました！

2021-01-16 18:13 UTC, Khmer495 approved these changes
lgtm

2021-01-17 12:20 UTC, merged